<?php

namespace Database\Seeders;

use App\Enums\Status;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          $doctors = [
            [
                'name'            => 'ডাঃ জাহাঙ্গীর আলম',
                'specialization'  => 'গাইনী ও অবস',
                'qualification'   => 'এমবিবিএস, এমএস (গাইনী এন্ড অবস)',
                'designation'     => 'সহকারী অধ্যাপক',
                'hospital_name'   => 'কসমোপলিটন হাসপাতাল, ফেনী',
                'visiting_hours'  => 'সকাল ৯টা – দুপুর ১টা, বিকাল ৫টা – রাত ৯টা',
                'days'            => 'শুক্র–শনিবার বাদে প্রতিদিন',
                'room_no'         => 'রুম-১০১, ১ম তলা',
                'visiting_fee'    => 700,
                'contact_number'  => '01812345678',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ জাহাঙ্গীর আলম'),
                'category_id'     => 1,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ সুমি আক্তার',
                'specialization'  => 'শিশু রোগ বিশেষজ্ঞ',
                'qualification'   => 'এমবিবিএস, এফসিপিএস (পেডিয়াট্রিক্স)',
                'designation'     => 'কনসালট্যান্ট',
                'hospital_name'   => 'ফেনী ক্লিনিক',
                'visiting_hours'  => 'বিকাল ৪টা – রাত ৮টা',
                'days'            => 'রবি – বৃহস্পতিবার',
                'room_no'         => 'রুম-২০৪, ২য় তলা',
                'visiting_fee'    => 500,
                'contact_number'  => '01798765432',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ সুমি আক্তার'),
                'category_id'     => 2,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ কামরুল হাসান',
                'specialization'  => 'মেডিসিন বিশেষজ্ঞ',
                'qualification'   => 'এমবিবিএস, এফসিপিএস (মেডিসিন)',
                'designation'     => 'সিনিয়র কনসালট্যান্ট',
                'hospital_name'   => 'সেন্ট্রাল হাসপাতাল, ঢাকা',
                'visiting_hours'  => 'সকাল ১০টা – বিকাল ৩টা',
                'days'            => 'সোম ও বুধবার',
                'room_no'         => 'রুম-৩০৫',
                'visiting_fee'    => 800,
                'contact_number'  => '01611223344',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ কামরুল হাসান'),
                'category_id'     => 3,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ নাসরিন জাহান',
                'specialization'  => 'চক্ষু বিশেষজ্ঞ',
                'qualification'   => 'এমবিবিএস, এমএস (অপথ্যালমোলজি)',
                'designation'     => 'সহকারী অধ্যাপক',
                'hospital_name'   => 'বঙ্গবন্ধু মেডিকেল বিশ্ববিদ্যালয়',
                'visiting_hours'  => 'সকাল ৯টা – দুপুর ২টা',
                'days'            => 'প্রতিদিন',
                'room_no'         => 'রুম-৪০১',
                'visiting_fee'    => 600,
                'contact_number'  => '01722334455',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ নাসরিন জাহান'),
                'category_id'     => 4,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ শহীদুল ইসলাম',
                'specialization'  => 'অর্থোপেডিক সার্জন',
                'qualification'   => 'এমবিবিএস, এমএস (অর্থোপেডিক্স)',
                'designation'     => 'কনসালট্যান্ট',
                'hospital_name'   => 'ঢাকা অর্থোপেডিক হাসপাতাল',
                'visiting_hours'  => 'বিকাল ৫টা – রাত ৯টা',
                'days'            => 'শুধুমাত্র সোম, বুধ, শুক্র',
                'room_no'         => 'রুম-৫০২',
                'visiting_fee'    => 1000,
                'contact_number'  => '01833445566',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ শহীদুল ইসলাম'),
                'category_id'     => 5,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ মাহমুদা হোসেন',
                'specialization'  => 'ডার্মাটোলজি ও ভেনেরোলজি',
                'qualification'   => 'এমবিবিএস, এফসিপিএস (ডার্মাটোলজি)',
                'designation'     => 'সহকারী অধ্যাপক',
                'hospital_name'   => 'চট্টগ্রাম মেডিকেল কলেজ',
                'visiting_hours'  => 'সকাল ১০টা – বিকাল ৪টা',
                'days'            => 'সোম–বৃহস্পতিবার',
                'room_no'         => 'রুম-৬০১',
                'visiting_fee'    => 700,
                'contact_number'  => '01944556677',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ মাহমুদা হোসেন'),
                'category_id'     => 6,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ ফরিদ আহমেদ',
                'specialization'  => 'নিউরোলজিস্ট',
                'qualification'   => 'এমবিবিএস, এফসিপিএস (নিউরোলজি)',
                'designation'     => 'সিনিয়র কনসালট্যান্ট',
                'hospital_name'   => 'ঢাকা মেডিকেল কলেজ হাসপাতাল',
                'visiting_hours'  => 'বিকাল ৩টা – রাত ৮টা',
                'days'            => 'মঙ্গল, বৃহস্পতি',
                'room_no'         => 'রুম-৭০৩',
                'visiting_fee'    => 1200,
                'contact_number'  => '01755667788',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ ফরিদ আহমেদ'),
                'category_id'     => 7,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ রুবিনা আক্তার',
                'specialization'  => 'কার্ডিওলজি',
                'qualification'   => 'এমবিবিএস, ডিএম (কার্ডিওলজি)',
                'designation'     => 'সহকারী অধ্যাপক',
                'hospital_name'   => 'জাতীয় হৃদরোগ ইনস্টিটিউট',
                'visiting_hours'  => 'সকাল ৯টা – দুপুর ২টা',
                'days'            => 'রবি–বৃহস্পতি',
                'room_no'         => 'রুম-৮০২',
                'visiting_fee'    => 1000,
                'contact_number'  => '01666778899',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ রুবিনা আক্তার'),
                'category_id'     => 8,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ মিজানুর রহমান',
                'specialization'  => 'ইউরোলজি',
                'qualification'   => 'এমবিবিএস, এমএস (ইউরোলজি)',
                'designation'     => 'কনসালট্যান্ট',
                'hospital_name'   => 'শেখ হাসিনা মেডিকেল বিশ্ববিদ্যালয়',
                'visiting_hours'  => 'সকাল ১০টা – বিকাল ৩টা',
                'days'            => 'সোম, বুধ, শুক্র',
                'room_no'         => 'রুম-৯০১',
                'visiting_fee'    => 900,
                'contact_number'  => '01877889900',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ মিজানুর রহমান'),
                'category_id'     => 5,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ তাহমিনা ইসলাম',
                'specialization'  => 'ডেন্টাল সার্জন',
                'qualification'   => 'বিডিএস, এমডিএস',
                'designation'     => 'সহকারী অধ্যাপক',
                'hospital_name'   => 'ঢাকা ডেন্টাল কলেজ',
                'visiting_hours'  => 'বিকাল ৪টা – রাত ৮টা',
                'days'            => 'রবি – বৃহস্পতি',
                'room_no'         => 'রুম-১০০১',
                'visiting_fee'    => 600,
                'contact_number'  => '01588990011',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ তাহমিনা ইসলাম'),
                'category_id'     => 6,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ আনিসুর রহমান',
                'specialization'  => 'গ্যাস্ট্রোএন্টারোলজি',
                'qualification'   => 'এমবিবিএস, এফসিপিএস (গ্যাস্ট্রো)',
                'designation'     => 'কনসালট্যান্ট',
                'hospital_name'   => 'ইবনে সিনা হাসপাতাল',
                'visiting_hours'  => 'সকাল ৯টা – দুপুর ১টা',
                'days'            => 'প্রতিদিন',
                'room_no'         => 'রুম-১১০২',
                'visiting_fee'    => 850,
                'contact_number'  => '01344556677',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ আনিসুর রহমান'),
                'category_id'     => 2,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'name'            => 'ডাঃ লুবনা পারভীন',
                'specialization'  => 'সাইকিয়াট্রি',
                'qualification'   => 'এমবিবিএস, এফসিপিএস (সাইকিয়াট্রি)',
                'designation'     => 'সিনিয়র কনসালট্যান্ট',
                'hospital_name'   => 'জাতীয় মানসিক স্বাস্থ্য ইনস্টিটিউট',
                'visiting_hours'  => 'বিকাল ৩টা – রাত ৮টা',
                'days'            => 'সোম–বৃহস্পতি',
                'room_no'         => 'রুম-১২০৩',
                'visiting_fee'    => 950,
                'contact_number'  => '01799887766',
                'profile_photo'   => null,
                'slug'            => Str::slug('ডাঃ লুবনা পারভীন'),
                'category_id'     =>4,
                'status'          => Status::ACTIVE->value,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
        ];

        DB::table('doctors')->insert($doctors);
    }
}
